# This is a basic workflow to help you get started with MATLAB Actions
name: MATLAB Multi-Version Matrix

# Controls when the action will run. 
on: 
  workflow_dispatch:          # Allows you to run this workflow manually from the Actions tab

permissions:
  contents: read
  pages: write
  id-token: write


env:
  PRODUCT_LIST: MATLAB MATLAB_Test MATLAB_Compiler MATLAB_Compiler_SDK Parallel_Computing_Toolbox
  MLM_LICENSE_TOKEN: ${{secrets.MLM_LICENSE_TOKEN}}

jobs:

  run-matlab-matrix:     
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        matlab-release: [R2024a,R2024b,R2025a]
      
 
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
       
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v3
        with:
          release: ${{ matrix.matlab-release }}
          cache: true
          products: ${{ env.PRODUCT_LIST }}
 
      - name: Run MATLAB Unit Tests
        uses: matlab-actions/run-tests@v3
        with:
          test-results-junit: allure-results/${{ matrix.matlab-release }}-results.xml
         
      - name: Upload Version Report Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: junit-report-${{ matrix.matlab-release }}
          path: allure-results/${{ matrix.matlab-release }}-results.xml
          retention-days: 5

  generate-allure-dashboard:
    needs: run-matlab-matrix
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Download All Matrix Reports
        uses: actions/download-artifact@v4
        with:
          pattern: junit-report-*
          path: combined-results

      - name: Move reports to a single directory
        run: | 
          mkdir final-results
          find combined-results/ -name "*.xml" -exec cp {} final-results/ \;

      - name: Load Allure History and Generate
        uses: simple-elf/allure-report-action@master
        with: 
          allure_results: final-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          



            
